version: '3.8'

services:
  etl:
    build: .
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ubaid
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=weather_db
    ports:
      - 5433:5432
